use std::{collections::HashMap, env, fs, io::Write, path::Path};

/// Codepoints with hand-drawn monochrome glyphs in emoji.rs TABLE, in order.
const TABLE_ENTRIES: &[(u32, &str)] = &[
    (0x2302, "house"),
    (0x2600, "sun"),
    (0x2601, "cloud"),
    (0x2602, "umbrella"),
    (0x2605, "star"),
    (0x260E, "telephone"),
    (0x2610, "ballot box"),
    (0x2611, "ballot box check"),
    (0x2639, "frowning face"),
    (0x263A, "smiling face"),
    (0x2665, "heart"),
    (0x266A, "note"),
    (0x2699, "gear"),
    (0x26A0, "warning"),
    (0x26A1, "lightning"),
    (0x2709, "envelope"),
    (0x2713, "check"),
    (0x2717, "ballot x"),
];

fn main() {
    let raw_dir = Path::new("../../assets/emoji/raw");
    let meta_json = Path::new("../../assets/emoji/meta/emoji_list.json");
    let emoji_index_json = Path::new("../../assets/emoji/meta/emoji_index.json");
    let openmoji_dir = Path::new("../../assets/emoji/openmoji-72x72-black");
    println!("cargo:rerun-if-changed=../../assets/emoji/raw");
    println!("cargo:rerun-if-changed=../../assets/emoji/meta/emoji_list.json");
    println!("cargo:rerun-if-changed=../../assets/emoji/meta/emoji_index.json");
    println!("cargo:rerun-if-changed=../../assets/emoji/openmoji-72x72-black");

    // Build hexcode → name and codepoint → name lookups from the full emoji JSON.
    let mut name_map: HashMap<u32, String> = HashMap::new();
    let mut name_by_hexcode: HashMap<String, String> = HashMap::new();
    if let Ok(data) = fs::read(meta_json) {
        if let Ok(entries) = serde_json::from_slice::<Vec<serde_json::Value>>(&data) {
            for entry in entries {
                if let (Some(hex), Some(name)) =
                    (entry["hexcode"].as_str(), entry["name"].as_str())
                {
                    name_by_hexcode.insert(hex.to_owned(), name.to_owned());
                    if let Ok(cp) = u32::from_str_radix(hex, 16) {
                        name_map.insert(cp, name.to_owned());
                    }
                }
            }
        }
    }

    let out_dir = env::var("OUT_DIR").unwrap();

    // --- raw_emoji.rs: static bitmap data for each .raw file ---
    let mut raw_entries: Vec<(u32, std::path::PathBuf)> = Vec::new();
    if let Ok(dir) = fs::read_dir(raw_dir) {
        raw_entries = dir
            .filter_map(|e| e.ok())
            .filter(|e| e.path().extension().map(|x| x == "raw").unwrap_or(false))
            .filter_map(|e| {
                let path = e.path();
                let stem = path.file_stem()?.to_str()?.to_owned();
                let hex = stem.strip_prefix("U+")?.to_owned();
                let cp = u32::from_str_radix(&hex, 16).ok()?;
                char::from_u32(cp)?;
                Some((cp, path))
            })
            .collect();
        raw_entries.sort_by_key(|(cp, _)| *cp);
    }

    let raw_rs = format!("{}/raw_emoji.rs", out_dir);
    let mut raw_out = fs::File::create(&raw_rs).unwrap();
    writeln!(raw_out, "// Generated by build.rs — do not edit").unwrap();
    writeln!(raw_out, "static RAW_EMOJI: &[(char, &[u8; 576])] = &[").unwrap();
    for (cp, path) in &raw_entries {
        let abs = fs::canonicalize(path).unwrap();
        writeln!(
            raw_out,
            "    ('\\u{{{:X}}}', include_bytes!(r\"{}\")),",
            cp,
            abs.display()
        )
        .unwrap();
    }
    writeln!(raw_out, "];").unwrap();

    // --- png_emoji.rs: openmoji PNGs decoded to 24x24 grayscale ---
    let raw_occupied: std::collections::HashSet<u32> =
        raw_entries.iter().map(|(cp, _)| *cp).collect();
    let table_set: std::collections::HashSet<u32> =
        TABLE_ENTRIES.iter().map(|(cp, _)| *cp).collect();

    let mut png_entries: Vec<(u32, String, std::path::PathBuf)> = Vec::new(); // (cp, hexcode, raw path)

    if let (Ok(index_data), true) = (fs::read(emoji_index_json), openmoji_dir.is_dir()) {
        if let Ok(index) = serde_json::from_slice::<serde_json::Value>(&index_data) {
            let emoji_raw_dir = format!("{}/emoji_raw", out_dir);
            fs::create_dir_all(&emoji_raw_dir).unwrap();

            if let Some(obj) = index.as_object() {
                for (hexcode, png_val) in obj {
                    let png_name = match png_val.as_str() {
                        Some(s) => s,
                        None => continue,
                    };

                    // Only single-codepoint entries (base + optional FE0F variation selector).
                    let parts: Vec<&str> = hexcode.split('-').collect();
                    if !parts[1..].iter().all(|p| *p == "FE0F") {
                        continue;
                    }

                    let cp = match u32::from_str_radix(parts[0], 16) {
                        Ok(v) => v,
                        Err(_) => continue,
                    };
                    if char::from_u32(cp).is_none() {
                        continue;
                    }
                    // Skip if covered by a hand-crafted raw or TABLE entry.
                    if raw_occupied.contains(&cp) || table_set.contains(&cp) {
                        continue;
                    }

                    let png_path = openmoji_dir.join(png_name);
                    if !png_path.exists() {
                        continue;
                    }

                    if let Some(raw_bytes) = process_openmoji_png(&png_path) {
                        let safe_name = hexcode.replace('-', "_");
                        let raw_file = format!("{}/{}.raw", emoji_raw_dir, safe_name);
                        fs::write(&raw_file, &raw_bytes).unwrap();
                        png_entries.push((cp, hexcode.clone(), std::path::PathBuf::from(raw_file)));
                    }
                }
            }
        }
    }
    png_entries.sort_by_key(|(cp, _, _)| *cp);

    let png_rs = format!("{}/png_emoji.rs", out_dir);
    let mut png_out = fs::File::create(&png_rs).unwrap();
    writeln!(png_out, "// Generated by build.rs — do not edit").unwrap();
    writeln!(png_out, "static PNG_EMOJI: &[(char, &[u8; 576])] = &[").unwrap();
    for (cp, _, path) in &png_entries {
        let abs = fs::canonicalize(path).unwrap();
        writeln!(
            png_out,
            "    ('\\u{{{:X}}}', include_bytes!(r\"{}\")),",
            cp,
            abs.display()
        )
        .unwrap();
    }
    writeln!(png_out, "];").unwrap();

    // --- emoji_list.rs: picker list combining TABLE glyphs + raw assets + PNG emoji ---
    let list_rs = format!("{}/emoji_list.rs", out_dir);
    let mut list_out = fs::File::create(&list_rs).unwrap();
    writeln!(list_out, "// Generated by build.rs — do not edit").unwrap();
    writeln!(list_out, "pub static EMOJI_LIST: &[EmojiEntry] = &[").unwrap();

    // Table entries first (monochrome glyphs, stable order).
    writeln!(list_out, "    // monochrome glyphs").unwrap();
    for (cp, name) in TABLE_ENTRIES {
        writeln!(
            list_out,
            "    EmojiEntry {{ codepoint: '\\u{{{:X}}}', name: \"{}\" }},",
            cp, name
        )
        .unwrap();
    }

    // Raw entries: skip any that duplicate a TABLE entry.
    let raw_only: Vec<_> = raw_entries
        .iter()
        .filter(|(cp, _)| !table_set.contains(cp))
        .collect();

    if !raw_only.is_empty() {
        writeln!(list_out, "    // raw bitmap assets").unwrap();
        for (cp, _) in raw_only {
            let name = name_map
                .get(cp)
                .map(|s| s.as_str())
                .unwrap_or("unknown");
            let name_escaped = name.replace('\\', "\\\\").replace('"', "\\\"");
            writeln!(
                list_out,
                "    EmojiEntry {{ codepoint: '\\u{{{:X}}}', name: \"{}\" }},",
                cp, name_escaped
            )
            .unwrap();
        }
    }

    // PNG emoji from openmoji.
    if !png_entries.is_empty() {
        writeln!(list_out, "    // openmoji PNG assets").unwrap();
        for (cp, hexcode, _) in &png_entries {
            let name = name_by_hexcode
                .get(hexcode.as_str())
                .map(|s| s.as_str())
                .unwrap_or("unknown");
            let name_escaped = name.replace('\\', "\\\\").replace('"', "\\\"");
            writeln!(
                list_out,
                "    EmojiEntry {{ codepoint: '\\u{{{:X}}}', name: \"{}\" }},",
                cp, name_escaped
            )
            .unwrap();
        }
    }

    writeln!(list_out, "];").unwrap();
}

/// Decode an openmoji PNG (72×72 palette/RGBA) and downsample to a 24×24
/// 8-level grayscale array (palette index 0=black … 7=white) composited
/// against a white background.
fn process_openmoji_png(path: &Path) -> Option<[u8; 576]> {
    let file = fs::File::open(path).ok()?;
    let mut decoder = png::Decoder::new(file);
    // Expand palette PNGs to RGBA/RGB; strip 16-bit to 8-bit.
    decoder.set_transformations(
        png::Transformations::EXPAND | png::Transformations::STRIP_16,
    );
    let mut reader = decoder.read_info().ok()?;
    let src_w = reader.info().width as usize;
    let src_h = reader.info().height as usize;

    let mut buf = vec![0u8; reader.output_buffer_size()];
    let frame = reader.next_frame(&mut buf).ok()?;

    let channels: usize = match frame.color_type {
        png::ColorType::Rgba => 4,
        png::ColorType::Rgb => 3,
        png::ColorType::GrayscaleAlpha => 2,
        png::ColorType::Grayscale => 1,
        _ => return None,
    };

    const DST: usize = 24;
    let mut out = [7u8; 576]; // default: white

    for oy in 0..DST {
        for ox in 0..DST {
            let sx0 = ox * src_w / DST;
            let sx1 = ((ox + 1) * src_w / DST).max(sx0 + 1).min(src_w);
            let sy0 = oy * src_h / DST;
            let sy1 = ((oy + 1) * src_h / DST).max(sy0 + 1).min(src_h);

            let mut gray_sum = 0u32;
            let mut count = 0u32;

            for sy in sy0..sy1 {
                for sx in sx0..sx1 {
                    let i = (sy * src_w + sx) * channels;
                    // Final gray (0=black, 255=white) composited against white.
                    let fg = match frame.color_type {
                        png::ColorType::Rgba => {
                            let r = buf[i] as u32;
                            let g = buf[i + 1] as u32;
                            let b = buf[i + 2] as u32;
                            let a = buf[i + 3] as u32;
                            let src_gray = (r * 77 + g * 150 + b * 29) >> 8; // luma
                            (255 * (255 - a) + src_gray * a) / 255
                        }
                        png::ColorType::Rgb => {
                            let r = buf[i] as u32;
                            let g = buf[i + 1] as u32;
                            let b = buf[i + 2] as u32;
                            (r * 77 + g * 150 + b * 29) >> 8
                        }
                        png::ColorType::GrayscaleAlpha => {
                            let gray = buf[i] as u32;
                            let a = buf[i + 1] as u32;
                            (255 * (255 - a) + gray * a) / 255
                        }
                        png::ColorType::Grayscale => buf[i] as u32,
                        _ => 255,
                    };
                    gray_sum += fg;
                    count += 1;
                }
            }

            if count > 0 {
                let avg = gray_sum / count;
                // Map 0..255 → 0..7 (0=black, 7=white).
                out[oy * DST + ox] = ((avg * 7 + 127) / 255).min(7) as u8;
            }
        }
    }
    Some(out)
}
