use std::{collections::HashMap, env, fs, io::Write, path::Path};

/// Codepoints with hand-drawn monochrome glyphs in emoji.rs TABLE, in order.
const TABLE_ENTRIES: &[(u32, &str)] = &[
    (0x2302, "house"),
    (0x2600, "sun"),
    (0x2601, "cloud"),
    (0x2602, "umbrella"),
    (0x2605, "star"),
    (0x260E, "telephone"),
    (0x2610, "ballot box"),
    (0x2611, "ballot box check"),
    (0x2639, "frowning face"),
    (0x263A, "smiling face"),
    (0x2665, "heart"),
    (0x266A, "note"),
    (0x2699, "gear"),
    (0x26A0, "warning"),
    (0x26A1, "lightning"),
    (0x2709, "envelope"),
    (0x2713, "check"),
    (0x2717, "ballot x"),
];

fn main() {
    let raw_dir = Path::new("../../assets/emoji/raw");
    let meta_json = Path::new("../../assets/emoji/meta/emoji_list.json");
    println!("cargo:rerun-if-changed=../../assets/emoji/raw");
    println!("cargo:rerun-if-changed=../../assets/emoji/meta/emoji_list.json");

    // Build codepoint → name lookup from the full emoji JSON.
    let mut name_map: HashMap<u32, String> = HashMap::new();
    if let Ok(data) = fs::read(meta_json) {
        if let Ok(entries) = serde_json::from_slice::<Vec<serde_json::Value>>(&data) {
            for entry in entries {
                if let (Some(hex), Some(name)) =
                    (entry["hexcode"].as_str(), entry["name"].as_str())
                {
                    if let Ok(cp) = u32::from_str_radix(hex, 16) {
                        name_map.insert(cp, name.to_owned());
                    }
                }
            }
        }
    }

    let out_dir = env::var("OUT_DIR").unwrap();

    // --- raw_emoji.rs: static bitmap data for each .raw file ---
    let mut raw_entries: Vec<(u32, std::path::PathBuf)> = Vec::new();
    if let Ok(dir) = fs::read_dir(raw_dir) {
        raw_entries = dir
            .filter_map(|e| e.ok())
            .filter(|e| e.path().extension().map(|x| x == "raw").unwrap_or(false))
            .filter_map(|e| {
                let path = e.path();
                let stem = path.file_stem()?.to_str()?.to_owned();
                let hex = stem.strip_prefix("U+")?.to_owned();
                let cp = u32::from_str_radix(&hex, 16).ok()?;
                char::from_u32(cp)?;
                Some((cp, path))
            })
            .collect();
        raw_entries.sort_by_key(|(cp, _)| *cp);
    }

    let raw_rs = format!("{}/raw_emoji.rs", out_dir);
    let mut raw_out = fs::File::create(&raw_rs).unwrap();
    writeln!(raw_out, "// Generated by build.rs — do not edit").unwrap();
    writeln!(raw_out, "static RAW_EMOJI: &[(char, &[u8; 576])] = &[").unwrap();
    for (cp, path) in &raw_entries {
        let abs = fs::canonicalize(path).unwrap();
        writeln!(
            raw_out,
            "    ('\\u{{{:X}}}', include_bytes!(r\"{}\")),",
            cp,
            abs.display()
        )
        .unwrap();
    }
    writeln!(raw_out, "];").unwrap();

    // --- emoji_list.rs: picker list combining TABLE glyphs + raw assets ---
    let list_rs = format!("{}/emoji_list.rs", out_dir);
    let mut list_out = fs::File::create(&list_rs).unwrap();
    writeln!(list_out, "// Generated by build.rs — do not edit").unwrap();
    writeln!(list_out, "pub static EMOJI_LIST: &[EmojiEntry] = &[").unwrap();

    // Table entries first (monochrome glyphs, stable order).
    writeln!(list_out, "    // monochrome glyphs").unwrap();
    for (cp, name) in TABLE_ENTRIES {
        writeln!(
            list_out,
            "    EmojiEntry {{ codepoint: '\\u{{{:X}}}', name: \"{}\" }},",
            cp, name
        )
        .unwrap();
    }

    // Raw entries: skip any that duplicate a TABLE entry.
    let table_set: std::collections::HashSet<u32> =
        TABLE_ENTRIES.iter().map(|(cp, _)| *cp).collect();
    let raw_only: Vec<_> = raw_entries
        .iter()
        .filter(|(cp, _)| !table_set.contains(cp))
        .collect();

    if !raw_only.is_empty() {
        writeln!(list_out, "    // raw bitmap assets").unwrap();
        for (cp, _) in raw_only {
            let name = name_map
                .get(cp)
                .map(|s| s.as_str())
                .unwrap_or("unknown");
            let name_escaped = name.replace('\\', "\\\\").replace('"', "\\\"");
            writeln!(
                list_out,
                "    EmojiEntry {{ codepoint: '\\u{{{:X}}}', name: \"{}\" }},",
                cp, name_escaped
            )
            .unwrap();
        }
    }

    writeln!(list_out, "];").unwrap();
}
