// Hand-crafted 24×24 palette-indexed (0-7) emoji from assets/emoji/raw/*.raw.
include!(concat!(env!("OUT_DIR"), "/raw_emoji.rs"));

// Openmoji 72×72 direct-grayscale (0-255) emoji decoded from PNGs at build time.
include!(concat!(env!("OUT_DIR"), "/png_emoji.rs"));

fn lookup_handcrafted(c: char) -> Option<&'static [u8; 24 * 24]> {
    RAW_EMOJI.iter().find(|(k, _)| *k == c).map(|(_, d)| *d)
}

fn lookup_png(c: char) -> Option<&'static [u8; 72 * 72]> {
    PNG_EMOJI.iter().find(|(k, _)| *k == c).map(|(_, d)| *d)
}

/// An entry in the built-in emoji list shown on the emoji keyboard layer.
pub struct EmojiEntry {
    pub codepoint: char,
    pub name: &'static str,
}

// EMOJI_LIST — generated by build.rs from TABLE_ENTRIES + assets/emoji/raw/*.raw.
// To add an emoji: drop a U+XXXX.png in assets/emoji/png/ and run `make emoji-assets`.
include!(concat!(env!("OUT_DIR"), "/emoji_list.rs"));

use embedded_graphics::{
    mono_font::MonoTextStyle,
    pixelcolor::Gray8,
    prelude::*,
    primitives::Rectangle,
    text::{Baseline, Text},
};

const SRC_W: i32 = 24;
const SRC_H: i32 = 24;

/// One 24×24 monochrome glyph. Each element is one row; bits 23..0
/// are the left-to-right pixels, bit 23 = leftmost.
type Glyph = [u32; SRC_H as usize];

/// Width of an emoji glyph in monospace cells. Holds for every entry
/// in the table — variable-width per glyph is intentionally not
/// supported, to keep layout math integer and predictable.
pub const EMOJI_CELL_SPAN: i32 = 2;

/// Lookup table of (Unicode scalar, bitmap) pairs. Sorted by code
/// point. Linear scan is fine — at this size it's faster than any
/// map and costs no allocation.
const TABLE: &[(char, Glyph)] = &[];

/// Look up the bitmap for `c`. Returns `None` for non-emoji code

pub enum EmojiSource {
    /// 24×24 palette-indexed (0-7) from hand-crafted .raw files.
    Raw(&'static [u8; 24 * 24]),
    /// 72×72 direct grayscale (0-255) from openmoji PNGs.
    Png(&'static [u8; 72 * 72]),
    /// 24×24 monochrome bitmap glyph.
    Glyph(&'static Glyph),
}

pub fn lookup(c: char) -> Option<EmojiSource> {
    if let Some(raw) = lookup_handcrafted(c) {
        return Some(EmojiSource::Raw(raw));
    }
    if let Some(png) = lookup_png(c) {
        return Some(EmojiSource::Png(png));
    }
    TABLE.iter().find(|(k, _)| *k == c).map(|(_, g)| EmojiSource::Glyph(g))
}

/// Returns true when [`draw_text`] would render `c` from the emoji
/// table or raw asset rather than from the fallback font.
pub fn is_emoji(c: char) -> bool {
    lookup(c).is_some()
}

/// Width of `c` in monospace cells, used by every layout, cursor,
/// and hit-test calculation in the text widgets. ASCII is 1 cell;
/// emoji are [`EMOJI_CELL_SPAN`].
pub fn cell_width(c: char) -> i32 {
    if is_emoji(c) {
        EMOJI_CELL_SPAN
    } else {
        1
    }
}

/// Sum [`cell_width`] across every char in `s`.
pub fn cells_in(s: &str) -> i32 {
    s.chars().map(cell_width).sum()
}

/// Draw `text` as a monospace run, substituting bitmaps from the
/// emoji table for any code points that have one and deferring to
/// `style.font` for everything else.
///
/// Text characters advance the pen by one font cell; emoji advance
/// by [`EMOJI_CELL_SPAN`] cells. Layout code that asks
/// [`cells_in`] for the width of a given slice will agree with what
/// this function actually paints.
pub fn draw_text<D>(
    canvas: &mut D,
    text: &str,
    pos: Point,
    style: MonoTextStyle<'_, Gray8>,
) -> Result<(), D::Error>
where
    D: DrawTarget<Color = Gray8>,
{
    let cell_w = style.font.character_size.width as i32;
    let cell_h = style.font.character_size.height as i32;
    let color = style.text_color.unwrap_or(super::palette::BLACK);
    let mut x = pos.x;
    let mut buf = [0u8; 4];
    for c in text.chars() {
        if let Some(emoji) = lookup(c) {
            let target = Rectangle::new(
                Point::new(x, pos.y),
                Size::new((cell_w * EMOJI_CELL_SPAN) as u32, cell_h as u32),
            );
            draw_glyph_in_rect_inner(canvas, &emoji, target, color)?;
            x += cell_w * EMOJI_CELL_SPAN;
        } else {
            let s = c.encode_utf8(&mut buf);
            Text::with_baseline(s, Point::new(x, pos.y), style, Baseline::Top).draw(canvas)?;
            x += cell_w;
        }
    }
    Ok(())
}

/// Render the glyph for `c` into `target`, scaled and aspect-
/// preserved. Returns `false` (without drawing) if `c` has no entry
/// in the emoji table or raw assets.
pub fn draw_glyph_in_rect<D>(
    canvas: &mut D,
    c: char,
    target: Rectangle,
    color: Gray8,
) -> Result<bool, D::Error>
where
    D: DrawTarget<Color = Gray8>,
{
    if let Some(emoji) = lookup(c) {
        draw_glyph_in_rect_inner(canvas, &emoji, target, color)?;
        Ok(true)
    } else {
        Ok(false)
    }
}

fn draw_glyph_in_rect_inner<D>(
    canvas: &mut D,
    emoji: &EmojiSource,
    target: Rectangle,
    _color: Gray8,
) -> Result<(), D::Error>
where
    D: DrawTarget<Color = Gray8>,
{
    let avail_w = target.size.width as i32;
    let avail_h = target.size.height as i32;
    if avail_w <= 0 || avail_h <= 0 {
        return Ok(());
    }
    let side = avail_w.min(avail_h);
    let off_x = target.top_left.x + (avail_w - side) / 2;
    let off_y = target.top_left.y + (avail_h - side) / 2;

    // Dispatch per source type — each has its own src dimensions and value interpretation.
    match emoji {
        EmojiSource::Png(data) => {
            // 72×72 direct grayscale (0=black, 255=white). Downsample to target with
            // area averaging for smooth rendering at any display size.
            const W: i32 = 72;
            const H: i32 = 72;
            for oy in 0..side {
                let sy0 = oy * H / side;
                let sy1 = ((oy + 1) * H / side).max(sy0 + 1);
                for ox in 0..side {
                    let sx0 = ox * W / side;
                    let sx1 = ((ox + 1) * W / side).max(sx0 + 1);
                    let mut acc = 0u32;
                    let mut count = 0u32;
                    for sy in sy0..sy1 {
                        for sx in sx0..sx1 {
                            acc += data[(sy * W + sx) as usize] as u32;
                            count += 1;
                        }
                    }
                    let avg = (acc + count / 2) / count;
                    // Double-quadratic contrast: x^4/255^3 pushes mid-grays toward
                    // black so thin lines (which average to ~25% coverage at 4:1
                    // downscale) stay visibly dark rather than washing out to light gray.
                    let d1 = avg * avg / 255;
                    let d2 = d1 * d1 / 255;
                    Pixel(Point::new(off_x + ox, off_y + oy), Gray8::new(d2 as u8)).draw(canvas)?;
                }
            }
        }
        EmojiSource::Raw(data) => {
            // 24×24 palette-indexed (0-7).
            for oy in 0..side {
                let sy0 = oy * SRC_H / side;
                let sy1 = ((oy + 1) * SRC_H / side).max(sy0 + 1);
                for ox in 0..side {
                    let sx0 = ox * SRC_W / side;
                    let sx1 = ((ox + 1) * SRC_W / side).max(sx0 + 1);
                    let mut acc = 0u32;
                    let mut count = 0u32;
                    for sy in sy0..sy1 {
                        for sx in sx0..sx1 {
                            acc += data[(sy * SRC_W + sx) as usize] as u32;
                            count += 1;
                        }
                    }
                    let avg = (acc + count / 2) / count;
                    Pixel(Point::new(off_x + ox, off_y + oy), palette_index_to_gray8(avg.min(7) as u8)).draw(canvas)?;
                }
            }
        }
        EmojiSource::Glyph(glyph) => {
            // 24×24 monochrome bitmap (bit-per-pixel, MSB = left).
            for oy in 0..side {
                let sy0 = oy * SRC_H / side;
                let sy1 = ((oy + 1) * SRC_H / side).max(sy0 + 1);
                for ox in 0..side {
                    let sx0 = ox * SRC_W / side;
                    let sx1 = ((ox + 1) * SRC_W / side).max(sx0 + 1);
                    let mut acc = 0u32;
                    let mut count = 0u32;
                    for sy in sy0..sy1 {
                        for sx in sx0..sx1 {
                            let row = glyph[sy as usize];
                            acc += if (row >> (SRC_W - 1 - sx)) & 1 != 0 { 0 } else { 7 };
                            count += 1;
                        }
                    }
                    let avg = (acc + count / 2) / count;
                    Pixel(Point::new(off_x + ox, off_y + oy), palette_index_to_gray8(avg as u8)).draw(canvas)?;
                }
            }
        }
    }
    Ok(())
}

/// Map a palette index (0..7) to the canonical SoulOS grayscale value.
fn palette_index_to_gray8(idx: u8) -> Gray8 {
    match idx {
        0 => Gray8::new(0),    // Black
        1 => Gray8::new(36),
        2 => Gray8::new(72),
        3 => Gray8::new(109),
        4 => Gray8::new(146),
        5 => Gray8::new(182),
        6 => Gray8::new(219),
        _ => Gray8::new(255),  // White
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn ascii_falls_through() {
        assert!(lookup('a').is_none());
        assert!(lookup(' ').is_none());
        assert!(lookup('!').is_none());
        assert!(!is_emoji('z'));
    }

    #[test]
    fn known_emoji_resolve() {
        assert!(is_emoji('\u{2665}')); // heart
        assert!(is_emoji('\u{2605}')); // star
        assert!(is_emoji('\u{2713}')); // check
        assert!(is_emoji('\u{2611}')); // checked box
    }

    #[test]
    fn table_is_sorted_by_code_point() {
        for w in TABLE.windows(2) {
            assert!(
                w[0].0 < w[1].0,
                "emoji table out of order: U+{:04X} should precede U+{:04X}",
                w[1].0 as u32,
                w[0].0 as u32,
            );
        }
    }

    #[test]
    fn cell_width_is_one_for_ascii() {
        assert_eq!(cell_width('a'), 1);
        assert_eq!(cell_width(' '), 1);
        assert_eq!(cell_width('Z'), 1);
    }

    #[test]
    fn cell_width_is_emoji_span_for_known_glyphs() {
        assert_eq!(cell_width('\u{2665}'), EMOJI_CELL_SPAN);
        assert_eq!(cell_width('\u{2611}'), EMOJI_CELL_SPAN);
    }

    #[test]
    fn cells_in_mixed_string() {
        // "h" + "i" + " " = 3 cells; "♥" = EMOJI_CELL_SPAN cells.
        assert_eq!(cells_in("hi \u{2665}"), 3 + EMOJI_CELL_SPAN);
        assert_eq!(cells_in(""), 0);
    }
}
